import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export default function TermsOfServicePage() {
  return (
    <div className="container mx-auto max-w-3xl py-10 px-4">
      <Button variant="outline" asChild className="mb-8">
        <Link href="/">
          <ArrowLeft className="mr-2 h-4 w-4" /> Back to Home
        </Link>
      </Button>
      <Card>
        <CardHeader>
          <CardTitle className="text-3xl">Terms of Service</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-muted-foreground leading-relaxed">
          <p><strong>Last Updated:</strong> {new Date().toLocaleDateString()}</p>

          <h2 className="text-xl font-semibold text-foreground pt-4">1. Acceptance of Terms</h2>
          <p>[TODO: Clearly state that using the app constitutes acceptance of these terms.]</p>
          <p>By accessing or using PromptCraft Pro ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of the terms, then you may not access the Service.</p>

          <h2 className="text-xl font-semibold text-foreground pt-4">2. Use of the Service</h2>
          <p>[TODO: Describe permitted uses and restrictions. E.g., age restrictions, prohibited activities like reverse engineering, distributing harmful content.]</p>
          <p>You agree to use PromptCraft Pro only for lawful purposes. You are responsible for the prompts you generate and use. You must not misuse the AI generation features.</p>

          <h2 className="text-xl font-semibold text-foreground pt-4">3. User Content (If applicable)</h2>
          <p>[TODO: If users can submit prompts to a public catalog, define ownership, rights granted to you, and responsibility for content.]</p>
          <p>For prompts you add to the local catalog, you retain ownership. If a future feature allows community sharing, specific terms for that content will be provided.</p>

          <h2 className="text-xl font-semibold text-foreground pt-4">4. AI Generated Content</h2>
          <p>[TODO: Disclaimer about AI-generated content – accuracy, appropriateness. User responsibility for reviewing and using AI content.]</p>
          <p>Prompts generated by the AI feature are for informational and creative purposes. We do not guarantee the accuracy, suitability, or quality of AI-generated content. You are responsible for reviewing and validating any AI-generated prompts before use.</p>
          
          <h2 className="text-xl font-semibold text-foreground pt-4">5. Affiliate Links & Advertising</h2>
          <p>[TODO: Disclosure about affiliate links and ads, if any.]</p>
          <p>PromptCraft Pro may display affiliate advertisements. We are not responsible for the content or practices of third-party websites linked through these ads.</p>

          <h2 className="text-xl font-semibold text-foreground pt-4">6. Intellectual Property</h2>
          <p>[TODO: State ownership of the app, its content (excluding user content if applicable), branding.]</p>
          <p>The Service and its original content (excluding user-generated prompts stored locally), features, and functionality are and will remain the exclusive property of PromptCraft Pro and its licensors.</p>

          <h2 className="text-xl font-semibold text-foreground pt-4">7. Termination</h2>
          <p>[TODO: Conditions under which access can be terminated.]</p>
          <p>We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>

          <h2 className="text-xl font-semibold text-foreground pt-4">8. Disclaimer of Warranties; Limitation of Liability</h2>
          <p>[TODO: Standard legal disclaimers – "as is" basis, no warranties, limit liability.]</p>
          <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranties, expressed or implied, regarding the Service. In no event shall PromptCraft Pro be liable for any indirect, incidental, special, consequential or punitive damages.</p>
          
          <h2 className="text-xl font-semibold text-foreground pt-4">9. Governing Law</h2>
          <p>[TODO: Specify the jurisdiction whose laws will govern the terms.]</p>
          <p>These Terms shall be governed and construed in accordance with the laws of [TODO: Your Jurisdiction], without regard to its conflict of law provisions.</p>

          <h2 className="text-xl font-semibold text-foreground pt-4">10. Changes to Terms</h2>
          <p>[TODO: Explain how updates to the terms will be communicated.]</p>
          <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.</p>

          <h2 className="text-xl font-semibold text-foreground pt-4">11. Contact Us</h2>
          <p>If you have any questions about these Terms, please contact us at: [TODO: Your Contact Email / Support Link]</p>
        </CardContent>
      </Card>
    </div>
  );
}
